group: edge
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directores:
    - $HOME/.gradle
    - .gradle
script:
  - ./gradlew build
notifications:
  on_failure: change # always|never
  on_success: never
